services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
  mysql-client:
    image: mysql:latest
    depends_on:
      mysql-server:
        condition: service_healthy
    container_name: mysql-client
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  website:
    build:
      context: website
      dockerfile: blabla.dockerfile
    depends_on:
      mysql-server:
        condition: service_healthy
    container_name: my-website
    ports:
      - "8120:80"
    
volumes:
  data: {}